version = 1

[merge]
require_automerge_label = false
method = "squash"
delete_branch_on_merge = true

[merge.message]
title = "pull_request_title"
body = "pull_request_body"
include_pr_number = true
strip_html_comments = true

[update]
always = true
require_automerge_label = false
