# Number of days of inactivity before an issue becomes stale
daysUntilStale: 91
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 77
# Issues with these labels will never be considered stale
exemptLabels:
  - 'not stale'
  - 'prio high'
  - 'security'
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Hi! This issue hasn't seen any activity recently. We close inactive issues after 90 days to manage
  the volume of issues we receive. If we missed this issue or you want to keep it open, please reply
  here. That will reset the timer and allow more time for this issue to be addressed before it is
  closed.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
unmarkComment: false
only: issues
