name: Bump version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semver type of new version (major / minor / patch)'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump-version:
    name: Bump version and create a new tag
    runs-on: ubuntu-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Setup Git
        run: |
          git config user.name 'Alexander Böhm'
          git config user.email '3983539+mheob@users.noreply.github.com'

      - name: Bump version
        run: yarn version ${{ github.event.inputs.version }}

      - name: Push latest version
        run: git push origin main --follow-tags
