name: Publish Extension

on:
  release:
    types:
      - created

jobs:
  publish:
    name: Publish to VS Code Marketplace
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Setup PNPM
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Publish to VS Code Marketplace
        run: pnpm deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
